### PR TITLE
Add martoon

### PR DESCRIPTION
**Pull request by gromakovsky**
He recently started working on Bridge, so we want him to have full
access to the `testing` server.

### CODE REVIEW

**Comment by balsoft** [comment]
You also have to update `serokell-nix` input

**Comment by gromakovsky** [comment]
Oh, there is no bot to do it. Where is out bot which updates `flake.lock` files configured? Can I add `stakerdao-infra` to the list of repos it controls?

**Comment by balsoft** [comment]
The list of repos is here: https://github.com/serokell/aquarius-infra/blob/master/servers/albali/update-daemon.nix#L19

I have added it just now, it will update on the next run.

**Comment by balsoft** [comment]
Actually, just re-triggered it

**Comment by gromakovsky** [comment]
Oh, nice. Just came back to my computer and the problem is already solved, thanks :smiley:

**Comment by balsoft** [comment]
Deployed

**Pull request merged**
